apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: realworld-db-daily-backup
  namespace: realworld-app
spec:
  schedule: "0 10 1 * * *" # Everyday at 01:10
  backupOwnerReference: self
  cluster:
    name: postgres
