apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: realworld-db-daily-backup
  namespace: realworld-app
spec:
  suspend: false
  schedule: "0 0 0 * * *" # At midnight every day
  backupOwnerReference: self
  cluster:
    name: postgres
