apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cnpg-monitor
  namespace: realworld-app
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: postgres
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
