apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: realworld-app
data:
    username: ENC[AES256_GCM,data:rxAP/L4uGlHT73nq,iv:Zx3QjBaELjGE27SAkRJdhtpOVDm2QALRliwCgIsbwwY=,tag:y+LlXZH9VFxmAdqdn2WzXg==,type:str]
    password: ENC[AES256_GCM,data:FelPiZdWganu3PdyQzZn+Q==,iv:88fHv3pFUPwCcr/uI9k/NmbYUsggIvcdcIu+TA591V8=,tag:gJ9AdXVscBmPGTaY5hEa3g==,type:str]
sops:
    lastmodified: "2026-01-02T23:23:46Z"
    mac: ENC[AES256_GCM,data:AwFAb93btqbO3nqcuDA6jUcSk/BakFgSu2Mchs1w/nYfOk1HAMTngrkCaYQfTxMNaarhOHOdPgO5RtvVv21I4CXaxuyiDK1htxJVrQPt4hRF4x5pY6dPIcjYIXffN9NEq0Z7W1e80cLiUoU4td0XZ42IYPUyISbdpYw2e4eUuAo=,iv:By1V44/Pyc3S5Uf48ZY/Vnzm9SHPoIDpWEqf0LnuH/Y=,tag:8EcYqA7+14tesTYkBUGXJA==,type:str]
    pgp:
        - created_at: "2026-01-02T23:23:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA07bJ8Xh3yEwAQ//cCScG/baQqFxFUlO8FY01jOP+vWsVQO0uGiachVihBuZ
            8b9LIUL6/qDFyiT8wAI5hfKayqsthQ3tLWfs0OHM26H076vIZavKrNjivoIg/xNv
            DAw2hdLpmsbLrye32RX6wnHyUxInzBirT2APgIIZu9EN6AM4pwENwVptIfhGFrAo
            yUsRw0gQnp0ZpKjerG/QINxZ7mMFXhYaUNYb2rcvQzb99mrkb9WSmabBtSg6BS9x
            7aCSMlXohTfWIwjupuutgfzJD6PyMAou/JyxLbCJ54JDW6L2V+36D/jvJccExMiz
            Y+1bslqtyCj1Sfn9EWygjlsApKLbAPyQFw2MUxVLP8P7EZMZshUEqcBoouUQOfyk
            ffDFArvj6uuchNyskDGUXBqDF2SjfTDGPlk0ROPZSAxLpmYy2pWdw4OAzzhzGVWO
            nSxlQKYuoZN616GVWwNVPxsHTlLausU3c3x40O5vHYdaNahrXROH0MZQTOffZPqr
            qbMWADJUVIL7H6aulyfR8sUoakVq/g4GIxBJxg/uOXpzE/2VJdWRVziADxLHnfD9
            3uvw1BxGRaBlbTWerm9yLWGrNv4YCQKwIt6+DJjSKksTtcc/fiLG6oX8VAeWeikP
            OwS+HkWJmYuiKNtcwwecQBb2WFbnqxLrH+4enzl7mA8O7BMbBFL+i98qv7+Qd1DS
            XAHW9JSrTAuuqDNIHnqo/NQIIDcILlP94WRnHnF0sP2zIXumCzJPTPWyUK0fOZUx
            EqeR2eaW9FbLmKu0EPj+oEN9qvy115qcZltec31L8D1Gk6v9CYWiicXVrAeh
            =XgwI
            -----END PGP MESSAGE-----
          fp: A3C5A8D20CA0C35395CB083EEC6B00FEF5418E18
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
