apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: realworld-app
stringData:
  username: ENC[AES256_GCM,data:cJGg8HqU,iv:6Rz3bd3wiQwFLGz9u66yEnsmRQENrGigiya0qdRT8wg=,tag:wPk4+sS01HOl3EX5rknGEg==,type:str]
  password: ENC[AES256_GCM,data:JmEVNjgC9ynuTA==,iv:SH2FZTE7ux1C07Duagg0onLiCri6p6IUfjNZuYzx1WQ=,tag:+VIIiibFxjseGr6yooOL5A==,type:str]
sops:
  lastmodified: "2026-01-03T02:35:41Z"
  mac: ENC[AES256_GCM,data:unk5dhuxwpTMOJg/3WE4wd8dLNDkvbTv+Pu2sPhTvte+VUNXN50ZP73Nw8094GCNUp87+aGN3MLZBhPPUlv2Xt3RX1XpkH/MGF7aYkW5snjXZZk1YEDrRRRbg7ScVaub6K/H8gEVoaDcjayEqaYL2w+Y+8pi+1HDtex+XRlMm7k=,iv:wruOq2lSKPncgummyX5WqjLnKTe7LH/Kv5kaytAp3Wc=,tag:NsT//V6yjzpsnT/dmoImLw==,type:str]
  pgp:
    - created_at: "2026-01-03T02:35:41Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA07bJ8Xh3yEwAQ//Rr4VQ2rj1udUzykdHsAvGwdaV+AZTYW2n0eyVd9xKJH7
        TRxCINugrPz5yOejwC+VmtF9swhWE+z9Yadoe59wSbP7AU4/yiEnkYIXkORMvM1n
        qmWc/rHrStGqkLXq6cAZmD4JLAElQJr/I4/nT2zikiOP05QO28WrIwXQFectA4o5
        puNBrz6Bw6YvCVOHI+3BmQpDSpOa4SoCoD5gQLzekMCAFwyYfuJVo9QL2SsmqMib
        Qev0gYrlF6IqKl3gt5xRM+zXK9ekkN2HttGWNXhxWtLEsAIxVdD0UZPoSQ6Q2FSb
        sBdtwOBZi6/4whmVn3iU6uUKE0m6C6gB+Kq2Rodqn8vemkiTBbtbqlI2qhq3r96C
        4aCpFMxnUxW3d4ofjOF/U+VwN19CroaO7CaqUp+F/TWA1lmj4voJur9otHmksqNu
        klA4VVQ2MWMTg7f6MYWBIceD7TTZNVes+JysaIs2gF79l28ruZfYRbDRrNuhF6c6
        c3HE0PvwahGS2p4TGdRR74UVn2vvuGzdym6/VH/4jra0Uu/HpU+JzQxs5Zrb4stf
        CHzuUYt6JM9VXLes8OEWNuAYZ1PGVYqwcsg8Tyz1gjNkGSx4q1NxYgZ9BvENywkC
        DsEYQCLgvFNwHRIuegHcvyc4attNVqtm+cIZ3NAJo+2ezTZOBK/HI00ro/YiZ9TS
        XgF3AxSXnegsOGCG/FKczCn39QaX6Rxzt6HTB/hLJcycU8nFCNmYwBlbfRL0kHqM
        ysRJPPOyOvYg1dnzAKqu1gwOhXXB+icfeEJjYX8QUOawsgWlae9efPjZlK+i0jU=
        =KVVP
        -----END PGP MESSAGE-----
      fp: A3C5A8D20CA0C35395CB083EEC6B00FEF5418E18
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
