apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: "{{ .Values.app.name }}"
    release: "{{ .Release.Name }}"
spec:
  type: "{{ .Values.deployment.type }}"
  selector:
    app: "{{ .Values.app.name }}"
  ports:
    - port: {{ .Values.deployment.port }}
      protocol: TCP
      targetPort: {{ .Values.deployment.targetPort }}
