apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - decryption-sops.yaml
  - helmrelease-app.yaml
  - imagepolicy-backend.yaml
  - imagepolicy-frontend.yaml
  - imagerepository.yaml
  - imageupdateautomation.yaml
