# Global settings
global:
  envSecretNames: []

namespace: ""
replicaCount: null

app:
  name: ""

deployment:
  image:
    repository: ""
    tag: ""
  type: ClusterIP
  port: null
  targetPort: null
