# Global settings
global:
  envSecretNames: []

namespace: ""
replicaCount: null

job:
  enabled: false
  command: []

app:
  name: ""

deployment:
  image:
    repository: ""
    tag: ""
  type: ClusterIP
  port: null
  targetPort: null
