apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: backend
  namespace: realworld-app
spec:
  interval: 10m
  chart:
    spec:
      chart: ./k8s/charts/realworld-app
      version: "0.2.4"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 10m
  values:
    global:
      envSecretNames:
        - "backend-secrets"
    migration:
      enabled: true
    app:
      name: backend
    replicaCount: 2
    deployment:
      image:
        repository: ghcr.io/nospooksallowed/realworld-fullstack-app
        tag: backend-92bee6222f019b2bd36d61f07a3d6d9fa9bb0823-95 # {"$imagepolicy": "flux-system:backend-policy:tag"}
      port: 3000
      targetPort: 3000
