apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: backend
  namespace: realworld-app
spec:
  interval: 10m
  chart:
    spec:
      chart: ./k8s/charts/realworld-app
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 10m
  values:
    global:
      envSecretNames:
        - "backend-secrets"
    replicaCount: 1
    enabled: true
    backend:
      image:
        tag: backend-bf4df8927f9a6404227949ab23a1b33c3c0239c9-93 # {"$imagepolicy": "flux-system:backend-policy:tag"}

