apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: backend
  namespace: realworld-app
spec:
  interval: 10m
  chart:
    spec:
      chart: ./k8s/charts/realworld-app
      version: "0.2.1"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 10m
  values:
    global:
      envSecretNames:
        - "backend-secrets"
    job:
      enabled: true
      command: ["npm", "run", "migrate:prod"]
    app:
      name: backend
    replicaCount: 2
    deployment:
      image:
        repository: ghcr.io/nospooksallowed/realworld-fullstack-app
        tag: backend-bf4df8927f9a6404227949ab23a1b33c3c0239c9-93 # {"$imagepolicy": "flux-system:backend-policy:tag"}
      port: 3000
      targetPort: 3000
