apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: realworld-app
type: Opaque
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:n6i5AQw439KjDHDBLmPGKB/zgq4a7fkA+VXXloLE6TcldBCoc+1YYR2c9u6YBKTSnL2crBvL2gYevKO80bR5b4DUg0Nc9VemOhr0gO0UavEh/A==,iv:Nol93ev7vGiNKgFxJeleh1B8J8a6ONjokC49ZRh8L2M=,tag:f4pN0xdDmeh9miN7dnHqfQ==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:+c2o4yWZ8qlK+jYmEYfWhMYWBDKOtkZTedz3p5mDBrlWFhYAaX6RFt+Rw+850llP9zT26sIagMZw6nsBcfeFKXkNZS+Mpsu/Wh57p04SsJg9npi5YD8FpQ==,iv:PpvD/BvCXQfyhd/azIFNQPPnNvBIGytAlt1aJzgt5C8=,tag:PAto4drDeWQTF047yx1i7w==,type:str]
sops:
  lastmodified: "2026-01-03T03:00:08Z"
  mac: ENC[AES256_GCM,data:ek3PDAPO7k7id6RL/QS6TxP2WbV414Tbz4jXla8a3sALsR9m9nMc5uZwEQK9pgjYn+ExCEbNyp9WhQJJVBNL+NHT1rd7l+8/VTYZMS678m731dn4B/0UVWTPTcMjzv+Rv3a1xXlS32VHaF0n60kIfkNihrNrxEFlEz8PYmLU1Ts=,iv:NCyBS4xZaDVnw3gPSSf3ZBgn8F50mO83kS2XGiJz3gY=,tag:RMnM2r3Mdho5ntVihWiZMQ==,type:str]
  pgp:
    - created_at: "2026-01-03T03:00:08Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA07bJ8Xh3yEwAQ/+KN4e//+7gqRSOgUJ6Hx/iZ5Is4mkqdoEHFS35XiKZHmF
        N3X+mR5TxawnNP1JNy+yoLHjMnkdwiqA8ApHEf2z0KA+iS1s146r34oFjmHuS8kb
        xC3so8J5zIbzLGk5XQyJsRY/KpkFdQ4CMGt84mJOfmRNJU0FxLgQOtqKaXLT+o3P
        n9O237XK7p/nniSi7Cy9efQOfvIr9EitP7tynXE0zoPCp6bHVoS05ieE6vQOEoyP
        c0P8r+etXEb4BYsj54Ctv2xigOfTxjqHUEzW6KTU+VnVqz/ELVYdli0fAiDxpa+x
        tsoxh/bwjuL1v5RU6gt4lB3adn3VmWEJc5e4IwkEkqyZP/oGYUupjKJkALug31te
        AVl6iIq8uppTNQApQdss4irbErBFiY4w4+rMxLPyUSUPdwYSPM6rltiqBpNpfOhz
        WzO3mXyC/LoU9eYcABOVwnUbPSeZUZC+TzL2hR1wQQBcL7LARGm65Vhnu203HicE
        kCHR+ZD/fa7ZrR0l2SQXOjGcQpg4Q5B+zyUlo2QVKQhWNspUMVwB6SgH3OVNcwgj
        DRYnKMQNIfpcx6Jt+jFD0RzKYSbsLzaX7UboBzzcXbySCkcs+vr8mHWPoP0X5VSl
        GSQ+tBqfkpcZOi/Zx2xAKxOsJApXYhaBxU1mZcrnz+n+qpK20gi68mafPg4WM2XS
        XgERvMbzX/E7SfuYIdl0HeMt/SP8mIQwe8WcBZY40unpPbXfqnXkvVAoCxR30PRv
        tvqR/nKIIDx+RQDtQdS9vBKTZhNHV7Vj2zmQCHaqSvGDjlysDLUcCd6pep2OHDQ=
        =1KpL
        -----END PGP MESSAGE-----
      fp: A3C5A8D20CA0C35395CB083EEC6B00FEF5418E18
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
