apiVersion: v1
kind: Secret
metadata:
    name: backend-secrets
    namespace: realworld-app
type: Opaque
data:
    DATABASE_URL: ENC[AES256_GCM,data:pAFFrHVfAqbfT9MMSmfVSY6a6ErWY+/4XNyGt6NUaKS1PEu+mSFrjWV2wg/CKV/rfry+e+gX+eHxyQXvHEEtNw==,iv:agfkEg41Hlq4FTVBjZmgsLE/XhaLwnVdJ4bGBhIBXPk=,tag:pQlM8B/fvEgQphamt/gBGg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:eTuR2IVOcEvah8m5UO/fPwKtx4v/3uTdlhvN1n0y56dLGMCF7Thv23bwZZ0X6sMQHlgfRz+dykHfLQap+KzxgoSZLcbQXdEjX9meaz7hZYNPxc67ANZqEGBROFRbg/tJOEoZFpyvu+tIxwV9+RC0pM1udD7E++9E,iv:FQi8x7dJpULgCxlv9JSqUghfBVCgnWbtFmWB7tvlYNc=,tag:ToAmWKSJZ86BNzRbjPlbhA==,type:str]
sops:
    lastmodified: "2025-11-23T03:45:01Z"
    mac: ENC[AES256_GCM,data:bAL63SQkyArq7OBERpT6ZUZL0LhKmmP6IWjJiNlLh93sxOQ3clmzzldDDCpC5h2V+wY76aZRArtb9BE7SE6p9Q5L1hZJqEQc+konbwzfRqEKFfMjtnbicX9EYMDZdQnMPs3bptAKGReivfAD+d+6EUyJy5AMDrb2Kgu/RgLur50=,iv:JqMY0lN8RGDZ8Rs32Z6oGJ0N4Mu64Ie2gjWyjgkQoKI=,tag:Wd00X91wvHU5tDQoLqMoww==,type:str]
    pgp:
        - created_at: "2025-11-23T03:45:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA07bJ8Xh3yEwARAAgl5mNF1A1BanKZwv4UM+Nxa/FvszRrRoBkROgiyycSwr
            YHqSTHE3YP6P14ve6B9bAnT9Rc1amZ2ko6ztECyxj90qxlrVW26HqU/iJvjcsM9A
            8BvFgUMAE6aBwxzcVu4whGjFA9Qcs0j3u0zrn8UiJjNvydzai/hpcUlDVGwXMArg
            Hkd5tmjMbcXY78CD7/f6aT1Krfn9eWeqV4k74VcIqeZOwPMRsiBvlSn9twAI7KaD
            QcOyBlQmEgIZi32J3O//abCpupf9pIJgARgdMsfnlcYrYbW91H65WgDmsST7Lm1z
            p4GNA8tMhAgkWx97J49Xtt/TcqP71cp/a+kQgnJZjO8dMEZIkBFv0Kt49RvFgTMP
            CX3awD+rQHbFOKhIyM+vJJznO5wGumsGvIBOe/hRbeu6R6VLwNOAc19/dUFbaq5F
            8SC48u9NXQCNv6wph5Acji6zVg7wTPPIQ6AQeC3SblBdbGQvkZvM9dmqbLoePjsG
            MJk+JE41FdAoo8YDGlU9yQgDJ++IztZSWL4+bE8VwJpPTSD6VbZnFM2IKMBHeKw9
            vmXRvBGQYERYfZIei57hoiXLS9+S3HM+IGb5lgljsTw5Xt1ggQs1UmSFiIRruUS9
            aY1Q3r79ZZZqK0jRoPsPhMOMWbAfeL7gidnOwC2ISVGywwxB4xuOQEebOzdW71PS
            XAGAqaFFwSTJVOUGmRIBcVBwVC+zYGJJ8wR1ATQsiv42rXWYhQvsMfrsoCfZz2y6
            VpsxUV+qJ6gc8n9TJ865lnNuxOXxarCYRRGsW97FcNZrFW9nTo/QJRu1Vrru
            =z3EK
            -----END PGP MESSAGE-----
          fp: A3C5A8D20CA0C35395CB083EEC6B00FEF5418E18
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
