apiVersion: v1
kind: Secret
metadata:
    name: backend-secrets-values
    namespace: realworld-app
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:CgD7Hcw+/IEhm+vJ2N0q1r/pF+mSnSDRAZlBCgPDTMMpNJ7/JRAbSwiFPcMh6Q6BILJi/gTCpgDoH7CoMleG5Wseo2+3yX7Hs0lsR17uKYDJXnox91iSNSmgbknqI0ihQmdV+3KxYXVv6JtVd/6Ghq77MBmuQlv3kaTCrR4uLRcLsgEJKP88Z9Rxwlb6m4grmW1yYsiu7adZORsnDNu+UsB594sJqE2JQgbW4h7qC4qbqqKIYnCM8IuSs8mz4wxsJ93Pn3uXhA6GUKA46cFwwC1zappxf/bw8Xr2D3QN1ROL+M2V2fTPiSTfJ5gtF6VE,iv:K63D4RtwCbjbU5gXCa2ThKFoQAP9nYmP3X7SW/GvFBM=,tag:Y3qDglSQDqkb8166hCtOAg==,type:str]
sops:
    lastmodified: "2025-11-08T23:38:45Z"
    mac: ENC[AES256_GCM,data:860vsm3uiDOS/jn+ro/JozWctKJ6HuHNyNnBAcW0eqA/ca3Wta1RzxF90/0yMGYE/HlpozYTIROHnpwcI2qRMs5lbMR6JJeXoAil2B8zSLI0JXxGTvf+kta46lEaVIIMhR8LgOrIAcWgqS15wLQwEpx16syoXwAw8TXKjyZDY6M=,iv:W28B69AldCpQ+HDj051E8Iho1h/dVCWvQ9OcgBxSc8Y=,tag:fDBBT8mL6PJK9DUI0/Hvjw==,type:str]
    pgp:
        - created_at: "2025-11-08T23:38:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA07bJ8Xh3yEwAQ//fH9VHsLE7gaM2nZ6Tn+jlinaC/IhvlVu9BLAfVr4Vfi3
            TqTJ2i606s7QQ6NaGFsShuBs0hzfn6WjVvgg+dYEtjtBOJDLkua1jDjUh2Kz6oEe
            yrbGHCS/FSqU/GTeQRY92+nTlGGq37KSw6igVySY8/vycOe7O3NghB0bYRNEZcYQ
            UOOZR1PUL2aUgoKOv/e/LPHtl2OV89TqU3uK10F/gyAnDtUMA4Diemxzz/w45/uv
            xFMudk6ti1eCj1iOb2Vc6JYM0pXcWSBkL+CzliCphgiE5bL20LtPcWl37pL9imae
            AEv9CSYzNZ+85ss/aj9YV3ANF22XbYs6JcDuXNvRgzLMJSxohxp5tloTmbbaB+y/
            u+Z0e4FLkmc+0EaZczMzPJI74OV6iF9CVTaO0iBPBPvYSq03KRY1accXuik5BUJh
            9ltA1xIJc6dgZVMgzZIOAzZlO/Rk7ZLXjowcoHKpX5/GWLle3BVun32D9VzI8zxY
            jiRl1LAhApo31BFvyryAD8sXJ2+HrWVcTqzWOz9Er4zyu/jSKV0L+tHb/J5s4Dy8
            mA+g1ibcntYDcJ3hxmm4JfeAMWuHQQMNx08pz/tlQESoQsUp8mQi0/Plvtz5Ie86
            PuiLTodfdJduJib7M28ZyIc3/JVFtpbeCc8k1OI4syNDFC2U+J7duJTzkAeycxrS
            XgH6N9CjodhQa29mTyIsP9vvHUBTV+bgIq7SVj1MjbnybOs/MnxVWrfHKpNRX+Pc
            9N7cmJOmuC3YOdeVxrT+PL8c5rxJHKmJyutkoI31f3rly+OIJZq6fpDWNdTRo3s=
            =OzSg
            -----END PGP MESSAGE-----
          fp: A3C5A8D20CA0C35395CB083EEC6B00FEF5418E18
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
