apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.secrets.backend.DATABASE_URL }}  
  JWT_SECRET: {{ .Values.secrets.backend.JWT_SECRET }}
