apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
  namespace: monitoring
type: Opaque
stringData:
  user: ENC[AES256_GCM,data:uMg6YMc=,iv:4lIBBUPLB8o76rPtvuyW1AqFLiLMOTc5P/EgsZWwd4w=,tag:hAonFmMJXXS/R9Zihxx82A==,type:str]
  password: ENC[AES256_GCM,data:8kgqyLaQSuZdPA==,iv:6YbmFUzbfWlbH5nOjTNio7ZbvrIG1hCFuN5KPIpgsGY=,tag:A2rzHtjoJ0/dOpbucxk1Fw==,type:str]
sops:
  lastmodified: "2026-01-16T21:14:32Z"
  mac: ENC[AES256_GCM,data:BdPkUTKFs16tHIODIzu2XLRpCu1PTREk7vnFu8ITP7gKBaIA/maKUUsg1aiJDUG8cfsrp1XXzgaPrBNRWFnMyUBZv4aqVOqTQiqFFHwwwZfvAZY+/5APXBUZ3pj3hEnQkfgnkJKFX8dceWgvsVzHx58Q5JFmCc7ccGyK6UCAzyI=,iv:eNv+P5+V/QZ13bTUnpsLmpLkQ7V5RuOFfTtwTkNXL3M=,tag:wWv5RnzxMykoSIXetzBNxQ==,type:str]
  pgp:
    - created_at: "2026-01-16T21:14:32Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA07bJ8Xh3yEwAQ//Sn5xw7W1zY4dSuyD3NsgXu9Cp0+Q75HrDD7CStJud6wT
        WLTcmu8xSE49d5qo4LDKAhQZRh4H5DnwhfA3Ynxkz71nUh2oBFqxdtwJAirxdbHJ
        Jj+0dqNPKaV+7+QrTAUVIxZVkEDxvQb1YGMiwsl7FhH0FucD53vonK3iUizZXe6L
        IWaux3tsRpfMY8C4/AcsA9hAgttbZR1Wy+pZPUk+VtiR+Y8nzlmh6Xzs/EfwhDH0
        RN3TcFEA2oMBFJRKNmMy8AMZRaO8P0Oq/2QfiEuHRZA7FovJiPT4KxxZ+ui6LWm9
        PqLup6HheC0pATHBI7iR+zqXrH9CR8X+mEQW/M+1+oBlzzs6j+GD1j4k8SoFF4WM
        VOyfI67DEywFxVLLqg53q8AO+KSe8XjyGVrwDPEq3sbN3mzcpXvFwzFTh1CKKhVD
        9rVlhmjXb7hgOfqSphwDMotKG1xJ5+Q6pWK3Lh7K0hLJF14eKcJ43tgMCepPixKH
        nwJHu0eg/D8EaDg98KUjNYU3enLqgrefOTnPdI1r65UkM5sAOgSYm+kbalBqZU5V
        sKeHPaOu3ua0hG7nFw8G22sOBaXBMl0gudxn2nUvaq7q29HYarvkcjhgH/G7XEcm
        XaoCHkdLxEMeo/SsdlJkUfl8O8rnRfHFyI8L6xfPZ9D0ysIi7OSA4BSZFxow+IbS
        XgFaNntVOD8Rghz7fDyid7XsUNHeziAsH2BL2yfp8FDkWWq/ZPF3NFVAbfsOd16L
        I0aIIpCZ8rMG5Nxdq6D5IIDaXYpNsu25CufID0S3p0EcRt2BqtfrYeX0zunvEFA=
        =AFYZ
        -----END PGP MESSAGE-----
      fp: A3C5A8D20CA0C35395CB083EEC6B00FEF5418E18
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
