apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frontend
  namespace: realworld-app
spec:
  interval: 10m
  chart:
    spec:
      chart: ./k8s/charts/realworld-app
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 10m
  values:
    app:
      name: frontend
    replicaCount: 1
    deployment:
      image:
        repository: ghcr.io/nospooksallowed/realworld-fullstack-app
        tag: frontend-bf4df8927f9a6404227949ab23a1b33c3c0239c9-93 # {"$imagepolicy": "flux-system:frontend-policy:tag"}
      port: 80
      targetPort: 8080
