apiVersion: v1
kind: Secret
metadata:
    name: backend-secrets-values
    namespace: realworld-app
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:o37hJlDrK6LJhSdeuiCU5ruuBKJCMQNkpDhitDcxtJ4HlFftbHhY324HXs/wxL2OAc5O3lRwvZKto6HDUgxB4PISaAWmNfCrYS/esjLBrsM1lR51sOyVZD4E0hZSBAFIuI1mOKtJ3ejBwMjyWJeofMlLcQv5/P9RYS2EEgbwSFPMST3zRyCTA1pLRhiGj0MGX8aCLWoRdoMJJf3cLgkQ3HzcUs5LuVlPyrM7Hn4f8ceHB0UraP0pLXdRMRBnJU0=,iv:siB7TB9mo2CGqoX+4UGBGDmlRmFgLmZQw7nNJ6P6r+4=,tag:c99gv/d7s7LzWd95eqFr7w==,type:str]
sops:
    lastmodified: "2025-11-08T21:14:04Z"
    mac: ENC[AES256_GCM,data:Whx1vVJgWeUtemfIfKO79eXGPwwg/0/frqBGPOi2LfyB76WxNnHQJnoqst6EbcQr29QU3rfB06QmXW1ap9wBSlSWbn02HpLrZ4T3adeO9jPoCsToOfVtHPCN8BpAY0kJCIkQa063UuAqt2FefPzH0r0I+S3e16mZc8cBPJs6pj0=,iv:JeQUmm0KqIk7U8FYBh6jZwexg/7ZQcrzLYfHS/YajrY=,tag:c/yJzVOb0Zc6ZkFWyhcccw==,type:str]
    pgp:
        - created_at: "2025-11-08T21:14:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA07bJ8Xh3yEwAQ//cBwVp1WyWd1QJOrUa9ieK3V5ZEXg3bcZFMf6PQDFtvCq
            i155a8wpT8QEDu/kdxoCKxZp7D3nM+EgsLmCY86omhsTHf1/R0K9LsQmheW9HrEw
            CC+xs0V9Slk6C4cjysqEyQbcepS1EsuQP7CbY7xe+rni1C9H7ZqYmdwXKLJTxoq0
            T8jpeqINRt8pBnO+lKB1aCChrOlzOxR+Ril50xrsydSRI6e7E4mtYhLwhl6XdPnn
            llOlYy1i25k0r/RgYDGw2cS/UqaCOj9Db3EwyK3JstPlY9dHmgYmCly7eMFfjOqZ
            J+5fU2qTwKD8DiNMdEt5w9358t75SyDrItY/XuiidfOKy357f/ojDpJ5BHt629ea
            CyMdc2MOvd9bhsPql4PhlgTUppRKPF5WtgrIzOLarYGB0aSY0hVXsi9lco29Kf04
            0zmesiZ3oD/vI7z/yNXKUULgEnlyyH1uiu9QSe6pamWH2bNv+d8pFLgGnIGF/eoM
            KdGbHcoEY4K9vQqPo7MmNSYkZInuuNWAN6n+vtVpBa5ibZNQJ8LdQ0gbLXgyJuYX
            C/7qyh9g+YOVYE4MIBM4zcantGspyjsIaOuvr/ZucyjABctPedUZHmKPDxVvheNf
            O3a0gyw4Xv37dDloPVGe5eTLw6HQWzj8jXPs8Oz5tOOTA/3b5U1JAfpfPuO4UTvS
            XAGRSTncIfehAQx+94PwinRXlbjYYHYGsS8aZWokuge0GjaDutJTJXXxc5BpcvhE
            IG3rm+QpVd84iDHmScfmcjHROFbq2TQ5wmzwg0SJlMo+WI0HAWS9SLCqvNv0
            =UePP
            -----END PGP MESSAGE-----
          fp: A3C5A8D20CA0C35395CB083EEC6B00FEF5418E18
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
