apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: realworld-app
  namespace: realworld-app
spec:
  interval: 10m
  chart:
    spec:
      chart: ./k8s/realworld-app-chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 10m
  values:
    replicaCount: 1
    backend:
      image:
        tag: backend-bf4df8927f9a6404227949ab23a1b33c3c0239c9-93 # {"$imagepolicy": "flux-system:backend-policy:tag"}
    frontend:
      image:
        tag: frontend-bf4df8927f9a6404227949ab23a1b33c3c0239c9-93 # {"$imagepolicy": "flux-system:frontend-policy:tag"}
  valuesFrom:
    - kind: Secret
      name: backend-secrets-values
      valuesKey: values.yaml
