apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: realworld-app
  namespace: realworld-app
spec:
  interval: 3m
  chart:
    spec:
      chart: ./k8s/realworld-app-chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 3m
  values:
    replicaCount: 1
    backend:
      tag: ghcr.io/nospooksallowed/realworld-fullstack-app:backend-2a806dce3473c9d82fc48ad9fe418b5df8216d32-78 # {"$imagepolicy": "flux-system:backend-policy"}
    frontend:
      tag: ghcr.io/nospooksallowed/realworld-fullstack-app:frontend-1144a2635ea433dc9baa7b4420e9f011c3961065-79 # {"$imagepolicy": "flux-system:frontend-policy"}
