apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: realworld-app
  namespace: realworld-app
spec:
  interval: 10m
  chart:
    spec:
      chart: ./k8s/realworld-app-chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 10m
  values:
    replicaCount: 3
    backend:
      image:
        tag: backend-1c930e8e80da96391d17cb1198765f6568f291b9-90 # {"$imagepolicy": "flux-system:backend-policy:tag"}
    frontend:
      image:
        tag: frontend-1c930e8e80da96391d17cb1198765f6568f291b9-90 # {"$imagepolicy": "flux-system:frontend-policy:tag"}
