apiVersion: image.toolkit.fluxcd.io/v2
kind: ImageRepository
metadata:
  name: realworld-app-images
  namespace: flux-system
spec:
  image: ghcr.io/nospooksallowed/realworld-fullstack-app
  interval: 1m
