apiVersion: image.toolkit.fluxcd.io/v2
kind: ImagePolicy
metadata:
  name: backend-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: realworld-app-images  
  filterTags:
    pattern: '^backend-[a-f0-9]+-(?P<run>[0-9]+)'
    extract: '$run'
  policy:
    numerical:
      order: asc
