apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: realworld-app
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Rc+NL08OJwceWoPP7JXBog==,iv:tOVIOAvHSqL+jCVf0lAKHkmB1dGeCdhy27L/g0vYl9M=,tag:QJR+C5Tif/hiscjYsmw8dQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:u+bwtQ==,iv:kNGDKB8N5S26/Ss/BOjUPdiwbDWnIrMfSQREyUJAFIY=,tag:XZ5AAmwbtS4iGejfjSTNjA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:RGi/LogupMp9h8q+,iv:ciaioSs/Z57jqirv7/OHV4LtP5/6JUMI9mgiq0nDGc0=,tag:gYyh0uBufqAi7wFz6Jw2TQ==,type:str]
sops:
    lastmodified: "2025-11-09T00:57:24Z"
    mac: ENC[AES256_GCM,data:edMmXmG+2YgrPVeQ1sr6ZDcglWRMtMJ8Mj/H2Olr55exEiwBbvO75OYLdfWq+d56htcDxH/qxLPvWY6X777nV+NeUlVPtQcLVv9yhGSivg0uKmrgBCC8eLIOPQvJuWQ9/xv+ao1e6TGq3G+KYUV7eI8ClV1gvaxR26xjOT8dYy4=,iv:ETPG0Sw32c8SginK1UlE4tQ2V4Utq/JSbkeQYtGvhHI=,tag:LjhyObJyVNhma5i5G7VQjg==,type:str]
    pgp:
        - created_at: "2025-11-09T00:57:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA07bJ8Xh3yEwAQ//Ufo2m7G59YzNtkbhT09SP/Vt7SSlgWi780ZFjFcR1yDF
            ZHnnA0UhhZBDuzpy43aTEOrDFIqqifNvMAFuwJPwHVkUPv3w+W0pQvdy/lXHTKR1
            XtWABYMbHaHpCTCv3zoTTQe5u4Cw8EYlbtLAmsDZ6Y90OpRMwmWHmhDprNfAOjn7
            PNzlFEGbKDZKI3mSuSpgY0lXvL2PhcPXjG+Dsf0fU+go/1yTtjGcY7aYVyvaIo3N
            FjSyJgZUYJGyp37U4dV6rC1HMpb3brz1mh/qePhTn+/QXTOvR5lUBG8n31tcY8Hy
            X0HK59hYBZyUlXS9vG3Gzcos6BAQKatCKBY3NKeh7ipiuuY0KG8skdp3eSw7KPQn
            IO2ux7QShjmMm3RuAiD3a1bTwTne9t/n391DiFZEdWSO0R2G0psM/dYekkTBgFF6
            E+aoBBdoNoWkZjKsfCXjGYuUSPnMfHJM6HAssF1vasDDtV/lHdE6VlWyDLqFHBj2
            PoL6KcPmXvgDmlXGGokrSgK+amyjSVjLZciIqDLbS8bh4wwqt3dOaiHEuEV8D3IO
            3sE5sDFKIB0BoPwVjz0i+tCQ18Lf/79SqkGxfqenATGT5qYURsRqAQ4RrVvphzHQ
            Yqwn/E1oULcBHPBbBTwv2TqkGnKc8WOucbn+fhJcA6zBypxwBu+2rsD4qRHsy4zS
            XgHm00SDlEQz97957tO5wKn3Kmvz7GIWn9XoPWw9QTX48eFS6mRd++0DCAw9WV9/
            JPuqMsvotwJc/R08YZoMwKHFhf+n8CuJypHQuUUUdDUd3+eNzTzm9JkNlDQ0WUM=
            =A+rb
            -----END PGP MESSAGE-----
          fp: A3C5A8D20CA0C35395CB083EEC6B00FEF5418E18
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
